ENV['RCT_NEW_ARCH_ENABLED'] = '1'

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'RnWalletExample' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )


  # Run Codegen during development for the example app.
  pre_install do |installer|
    system("cd ../../ && npx bob build --target codegen")
  end

  # pn setup
  pod "Thresh", '1.4.11'
  pod "ParticleMPCCore", '1.4.11'
  pod "ParticleAuthCore", '1.4.11'
  pod "AuthCoreAdapter", '1.4.11'

  pod 'ParticleNetworkBase', '1.4.10'
  pod 'ConnectCommon',  '0.2.24'

  pod 'SwiftyUserDefaults', :git =>'https://github.com/SunZhiC/SwiftyUserDefaults.git', :branch =>'master'
  pod 'SkeletonView', :git =>'https://github.com/SunZhiC/SkeletonView.git', :branch =>'main'

  # pod 'Thresh'
  # pod 'ParticleMPCCore'
  # pod 'ParticleAuthCore'
  # pod 'AuthCoreAdapter'

  # pod 'ParticleNetworkBase'
  # pod 'ParticleNetworkChains'
  # pod 'ConnectCommon'

  # pod 'SwiftyUserDefaults', :git => 'https://github.com/SunZhiC/SwiftyUserDefaults.git', :branch => 'master'
  # pod 'SkeletonView', :git => 'https://github.com/SunZhiC/SkeletonView.git', :branch => 'main'
  # # pod 'WalletConnectSwiftV2', :git => 'https://github.com/SunZhiC/WalletConnectSwiftV2.git', :branch => 'particle'

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    # 配置pn
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
        # config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      end
    end

    # installer.target_installation_results.pod_target_installation_results.each do | pod_name, target_installation_result|
    #   target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
    #     resource_bundle_target.build_configurations.each do |config|
    #       config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
    #     end
    #   end
    # end

  end
end
